### ISSUE TITLE
No module named master_slave_connection

### ISSUE THREAD

**Issue by WellDone2094** [jarus/flask-mongokit#21]
Hi i'm try to run a basic flask application but when i try to run "from flask.ext.mongokit import MongoKit, Document" i get this error:

Traceback (most recent call last):
  File "todo.py", line 4, in <module>
    from flask.ext.mongokit import MongoKit, Document
  File "/Users/shiller/Desktop/app/venv/lib/python2.7/site-packages/flask/exthook.py", line 81, in load_module
    reraise(exc_type, exc_value, tb.tb_next)
  File "/Users/shiller/Desktop/app/venv/lib/python2.7/site-packages/flask_mongokit.py", line 16, in <module>
    from mongokit import Connection, Database, Collection, Document
  File "/Users/shiller/Desktop/app/venv/lib/python2.7/site-packages/mongokit/**init**.py", line 40, in <module>
    from master_slave_connection import MasterSlaveConnection
  File "/Users/shiller/Desktop/app/venv/lib/python2.7/site-packages/mongokit/master_slave_connection.py", line 7, in <module>
    from pymongo.master_slave_connection import MasterSlaveConnection as PymongoMasterSlaveConnection
ImportError: No module named master_slave_connection

This is my pip freeze:

Flask==0.10.1
Flask-MongoKit==0.6
itsdangerous==0.24
Jinja2==2.7.3
MarkupSafe==0.23
mongokit==0.9.1.1
pymongo==3.0
Werkzeug==0.10.4

**Comment by WellDone2094** [comment]
solved with downgrade to pymongo==2.8

**Comment by shennian** [comment]
thx

**Comment by step21** [comment]
thx
